config/routes.rb
Rails.application.routes.draw do
   root :to => 'channel/balances#index'
  match '/visit' => 'home#list'
  match '/vamp/mtkbook/details.aspx' => 'books#details'
  match 'cminterface/sms/sync.aspx' => 'books#sync'
  match '/resource/books/cover/:id.:format' => 'book_covers#show'
  match '/resource/books/cover/' => 'book_covers#show'
  match '/tools/:action' => 'tools'
  match '/cmreader(/:action)' => 'cmreader'
  
  namespace :admin do
    resources :books
    resources :bk_histories
    resources :book_chapters
    resources :companies
    resources :customers
    resources :channels
    resources :balances
    resources :imports
    resources :operates
    resources :book_types do
      match 'add' => 'book_types#addtype'
    end
    resources :book_clients
    resources :charts
    resources :cm_users
    resources :cm_logins
    resources :bk_clients
    resources :bk_toplists
    match 'book_configuration(/:action/(:id))' => 'book_configuration#index'
    match 'tools' => 'tools'
    match 'balances(/:action)' => 'balances'
    match 'companies/:id/save_customer' => 'companies#save_customer'
    match 'operates/:action' => 'operates'
    match 'activetion/(:action)' => 'activetion'
    match 'bk_toplists(/:action)' => 'bk_toplists'
  end
  
  namespace :reader do
    resources :books
    match 'pages/:action' => 'pages'
    match 'pages/books/:id(/:op(/:ch))' => 'pages#books'
    match 'sync/:action' => 'sync'
    match 'logs/:action' => 'logs'
    match 'pages/toplist/:id' => 'pages#toplist'
    match 'pages/collection_book/:id' => 'pages#collection_book'
    match 'activetion/(:action)' => 'activetion'
  end

  scope '/~bkb4info' do
    namespace :reader do
      resources :books
      match 'pages/:action' => 'pages'
      match 'pages/books/:id(/:op(/:ch))' => 'pages#books'
      match 'sync/:action' => 'sync'
      match 'logs/:action' => 'logs'
      match 'pages/toplist/:id' => 'pages#toplist'
      match 'pages/collection_book/:id' => 'pages#collection_book'
      match 'activetion/(:action)' => 'activetion'
    end
    namespace :channel do
      match 'balances' => 'balances#index'
    end
   
  end

  
  namespace :channel do
    match 'balances' => 'balances#index'
  end
  
  
  match 'home/test' => 'home#test_here'
  
  
end

app/models/Customer.rb
class Customer < ActiveRecord::Base
	belongs_to :company
	belongs_to :user
end

app/models/balance.rb
class Balance < ActiveRecord::Base
	belongs_to :company
	belongs_to :product
end

app/models/bk_client.rb
class BkClient < ActiveRecord::Base

end

app/models/bk_favorite.rb
class BkFavorite < ActiveRecord::Base
  
 def self.add_favorite(cl_id,booksid)
    f = BkFavorite.new
    f.client_id = cl_id
    f.book_id = booksid
    f.save
  end
  
end

app/models/bk_history.rb
class BkHistory < ActiveRecord::Base
  belongs_to :book
  belongs_to :book_chapter
  
  def self.add_history(client_id, book_id, chapter_id)
    h = BkHistory.new
    h.client_id = client_id
    h.book_id = book_id
    h.chapter_id = chapter_id
    h.save
  end
end

app/models/bk_hotsite.rb
class BkHotsite < ActiveRecord::Base
end

app/models/bk_log.rb
class BkLog < ActiveRecord::Base
  belongs_to :book
  belongs_to :book_chapter
  belongs_to :bk_client, :foreign_key => 'client_id' 
  
  def self.add_history(client_id, book_id, chapter_id)
    log = BkLog.new
    log.client_id = client_id
    log.book_id = book_id
    log.chapter_id = chapter_id
    log.operate = 'read history'
    log.url = "/reader/pages/books/#{book_id}/chapters/#{chapter_id}"
    log.save
    
  end
end

app/models/bk_toplist.rb
class BkToplist < ActiveRecord::Base
end

app/models/book.rb
class Book < ActiveRecord::Base
	has_and_belongs_to_many :book_types
	has_many :book_chapters
	has_many :bk_histories
	

end

app/models/book_chapter.rb
class BookChapter < ActiveRecord::Base
	belongs_to :book
end

app/models/book_client.rb
class BookClient < ActiveRecord::Base
end

app/models/book_type.rb
class BookType < ActiveRecord::Base
	has_and_belongs_to_many :books
end

app/models/channel.rb
class Channel < ActiveRecord::Base
	belongs_to :company
end

app/models/cm_db_operate.rb
class CmDbOperate < ActiveRecord::Base
end

app/models/cm_login.rb
class CmLogin < ActiveRecord::Base
	belongs_to :cm_user
end

app/models/cm_operate.rb
class CmOperate < ActiveRecord::Base
end

app/models/cm_user.rb
class CmUser < ActiveRecord::Base
   def self.add_user(userid, channel)
    u = CmUser.new
    u.userid = userid
    u.channel = channel
    u.save
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
	has_and_belongs_to_many :product_usages
	has_many :channels
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	belongs_to :company
	belongs_to :user
end

app/models/posted_data.rb
class PostedData < ActiveRecord::Base
end

app/models/product_usage.rb
class ProductUsage < ActiveRecord::Base
	has_and_belongs_to_many :companies
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :token_authenticatable, :registerable, :recoverable,
         :rememberable, :trackable, :validatable, :encryptable, :encryptor => "authlogic_sha512"

  has_many :orders
  has_and_belongs_to_many :roles
  belongs_to :ship_address, :foreign_key => "ship_address_id", :class_name => "Address"
  belongs_to :bill_address, :foreign_key => "bill_address_id", :class_name => "Address"

  before_save :check_admin
  before_validation :set_login

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :persistence_token, :login

  scope :admin, lambda { includes(:roles).where("roles.name" => "admin") }
  scope :registered, where("users.email NOT LIKE ?", "%@example.net")

  # has_role? simply needs to return true or false whether a user has a role or not.
  def has_role?(role_in_question)
    roles.any? { |role| role.name == role_in_question.to_s }
  end

  # Creates an anonymous user.  An anonymous user is basically an auto-generated +User+ account that is created for the customer
  # behind the scenes and its completely transparently to the customer.  All +Orders+ must have a +User+ so this is necessary
  # when adding to the "cart" (which is really an order) and before the customer has a chance to provide an email or to register.
  def self.anonymous!
    token = User.generate_token(:persistence_token)
    User.create(:email => "#{token}@example.net", :password => token, :password_confirmation => token, :persistence_token => token)
  end

  def self.admin_created?
    User.admin.count > 0
  end

  def anonymous?
    email =~ /@example.net$/
  end

  def deliver_password_reset_instructions!
    reset_perishable_token!
    UserMailer.password_reset_instructions(self).deliver
  end

  protected
  def password_required?
    !persisted? || password.present? || password_confirmation.present?
  end
  
  def self.find_for_database_authentication(warden_conditions)
  	conditions =  warden_conditions.dup
  	login = conditions.delete(:login)
  	where(conditions).where(["lower(login) = :value OR lower(email) = :value", { :value => login.downcase }]).first
  end

  private

  def check_admin
    return if self.class.admin_created?
    admin_role = Role.find_or_create_by_name "admin"
    self.roles << admin_role
  end

  def set_login
    # for now force login to be same as email, eventually we will make this configurable, etc.
    self.login ||= self.email if self.email
  end

  # Generate a friendly string randomically to be used as token.
  def self.friendly_token
    ActiveSupport::SecureRandom.base64(15).tr('+/=', '-_ ').strip.delete("\n")
  end

  # Generate a token by looping and ensuring does not already exist.
  def self.generate_token(column)
    loop do
      token = friendly_token
      break token unless find(:first, :conditions => { column => token })
    end
  end

  def self.current
    Thread.current[:user]
  end

  def self.current=(user)
    Thread.current[:user] = user
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < Admin::BaseController
  resource_controller
end

app/views/admin/customers/_form.html.erb
<fieldset>
  <%= f.field_container :user_id do %>
    <%= f.label :user_id, '登录用户号' %> <span class="required">*</span><br />
    <%= f.text_field :user_id, :class => 'fullwidth title'  %>
    <%= f.error_message_on :user_id %>
  <% end %>	
  <%= f.field_container :company_id do %>
    <%= f.label :company_id, '公司名' %> <span class="required">*</span><br />
    <%= f.text_field :company_id, :class => 'fullwidth title'  %>
    <%= f.error_message_on :company_id %>
  <% end %>
    <%= f.field_container :real_name do %>
    <%= f.label :real_name, '真实姓名' %> <span class="required">*</span><br />
    <%= f.text_field :real_name, :class => 'fullwidth title'  %>
    <%= f.error_message_on :real_name %>
  <% end %>
  <%= f.field_container :phone do %>
    <%= f.label :phone, '联系电话' %> <span class="required">*</span><br />
    <%= f.text_field :phone, :class => 'fullwidth title'  %>
    <%= f.error_message_on :phone %>
  <% end %>
    <%= f.field_container :website do %>
    <%= f.label :website, '网站' %> <span class="required">*</span><br />
    <%= f.text_field :website, :class => 'fullwidth title'  %>
    <%= f.error_message_on :website %>
  <% end %>  
</fieldset>

app/views/admin/customers/edit.html.erb
<%= render :partial => 'admin/shared/data_sub_menu' %>

<h1>修改顾客资料</h1>


<%= form_for(@customer, :url => object_url, :html => { :method => :put, :multipart => true }) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= render :partial => 'admin/shared/edit_resource_links' %>
<% end %>

app/views/admin/customers/index.html.erb
<%= render :partial => 'admin/shared/data_sub_menu' %>

<div class='toolbar'>
  <ul class='actions'>
    <li id="new_customer_link">
      <%= button_link_to t("new_customer"), new_object_url %>
    </li>
  </ul>
  <br class='clear' />
</div>

<h1>客户列表</h1>

<table>
	<thead>
		<th>ID</th>
		<th>User ID</th>
		<th>公司名</th>
		<th>姓名</th>
		<th>联系电话</th>
		<th>网站</th>
		<th>开通时间</th>
		<th>更新日期</th>
	</thead>
	<tbody>
		<% collection.each do |c| %>
		<tr>
			<td><%= c.id%></td>
			<td><%= c.user_id%></td>
			<td><%= c.company_id%></td>
			<td><%= c.real_name%></td>
			<td><%= c.phone%></td>
			<td><%= c.website%></td>
			<td><%= c.created_at%></td>
			<td><%= c.updated_at%></td>
		</tr>
		<% end%>
	</tbody>
</table>

app/views/admin/customers/new.html.erb
<%= render :partial => 'admin/shared/data_sub_menu' %>

<h1>添加新客户</h1>

<%= form_for(:customer,  :url => collection_url, :html => { :multipart => true }) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= render :partial => 'admin/shared/new_resource_links' %>
<% end %>

app/views/admin/customers/show.html.erb
<%= render :partial => 'admin/shared/data_sub_menu' %>





<%= render :partial => 'admin/shared/show_resource_links' %>